### ISSUE TITLE
Garlicion mining error

### ISSUE THREAD

**Issue by CapitalJay** [garlicoin-project/garlicore-garlicoin#1]
This issue tracker is only for technical issues related to garlicoin-core.

General garlicoin questions and/or support requests and are best directed to the [garlicointalk.io forums](https://garlicointalk.io/).

For reporting security issues, please contact the Garlicoin developers on the #garlicoin-dev Freenode IRC channel or alternatively you can email us at contact@garlicoin.org.

### Describe the issue
I have installed the garlicion mining program and I have come across two errors saying "qt/test/test_garlicoin-qt" and
"test/test_garlicoin"
it sends me to these sites
"See src/test-suite.log
Please report to https://github.com/garlicoin-project/garlicoin/issues"
if i go to these addresses nothing comes up showing me how to fix them and i was wondering how to fix these errors

**Comment by ryan-shaw** [comment]
Looks like the links were incorrectly changed - here is the official repo https://github.com/GarlicoinOrg/Garlicoin
